### PR TITLE
Fix dynamic library usage on iOS

### PR DESCRIPTION
**Pull request by kuhnroyal**
* attempt to run integration test on an older iOS version as well

### CODE REVIEW

**Comment by kuhnroyal** [comment]
There doesn't seem to be an easy way of running the integration tests on older simulators with Github actions.

**Comment by simolus3** [comment]
Thank you for this fix :+1: I don't think we need to run tests on older simulators, we can check the compile-time options in the test output.
I think it also makes sense to fallback to `DynamicLibrary.process()` if we can't load the proper library (you can catch the `ArgumentError`). That would also help for people using the sqlcipher variant.

**Comment by kuhnroyal** [comment]
Ok, I can do that.
I don't see a difference in the compile-time options compared to the latest master build.

**Comment by kuhnroyal** [comment]
After looking at sqlcipher_flutter_libs I am actually not sure why `process()` works there (it is 3.33.0). I assume that it might be statically linked due to the definition of `"HEADER_SEARCH_PATHS": "$(PODS_ROOT)/SQLCipher"` in its podspec.

**Comment by kuhnroyal** [comment]
`sqlite3_flutter_libs` should in theory also work for MacOS, not sure if the podspec needs changes for that but the same fallback mechanism could be applied there as well.

**Comment by simolus3** [comment]
For macOS support, I think we'd need another entry in the pubspec and a `macos` folder similar to the current `ios` folder in `sqlite_flutter_libs` too.

**Pull request merged**
